# deploy.yml

name: deploy

on:
  # 원래 여기에 push 이벤트가 들어갔어야 하는데 `workflow_dispatch`라는 키워드가 들어갔죠?
  # 즉, "workflow를 수동으로 trigger시킬게"라는 의미입니다.
  workflow_dispatch:
    # 값도 받을 수 있습니다. region, env 말고 원하시는 값들을 받을 수도 있겠죠?
    inputs:
      region:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 수동으로 workflow를 trigger시켰을 때 `inputs`값이 잘 들어오는지 확인해줍니다.
      - name: Echo variables
        run: |
          # 이전 글에서 배포할 브랜치(ex. deploy/twn/qa/test)를 push하고 파싱하여
          # region(twn)과 env(qa)값을 가져왔었는데요, 이젠 그럴 필요가 없습니다.
          # `workflow_dispatch`를 이용하면 `github.event.inputs`이라는 키워드로 원하는 값을 받을 수 있습니다.
          # region, env는 어떻게 받냐구요? 글을 쭉 읽어주세요!
          echo "env: ${{ github.event.inputs.env }}"
          echo "region: ${{ github.event.inputs.region }}"
